singleQuote: true
semi: false
printWidth: 100
trailingComma: none

plugins:
  - prettier-plugin-sql
language: 'sqlite'
keywordCase: 'upper'
dataTypeCase: 'upper'
functionCase: 'upper'
expressionWidth: 100
